definitions:
  contact__site_page:
    enabled: false
    menu_name: footer
    parent: ''
    expanded: false
    weight: 0
  standard__front_page:
    weight: -50
    menu_name: main
    parent: ''
    enabled: false
    expanded: false
  user__logout:
    enabled: false
    menu_name: account
    parent: ''
    expanded: false
    weight: 10
  search__view:
    menu_name: tools
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  user__page:
    menu_name: account
    parent: ''
    weight: -10
    expanded: false
    enabled: true
_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
