selector: .container
top_spacing: '2'
bottom_spacing: '2'
class_name: is-sticky
wrapper_class_name: sticky-wrapper
center: 0
get_width_from: ''
width_from_wrapper: 1
responsive_width: 0
z_index: '10'
